default:
  #default days after the first death to plot (number)
  days: 26

  #default countries eg: brazil;são paulo;italy; spain;US; united kingdom
  countries: brazil;são paulo;italy; spain;US; united kingdom

  #default logarithmic plot ex: checked or empty
  is_log: checked